// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetRequestByID(arg1) {
  return window['go']['main']['App']['GetRequestByID'](arg1);
}

export function GetResponseByID(arg1) {
  return window['go']['main']['App']['GetResponseByID'](arg1);
}

export function ParseCurlCommand(arg1) {
  return window['go']['main']['App']['ParseCurlCommand'](arg1);
}
