// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteRequest(arg1:main.RequestData):Promise<main.ResponseData>;

export function GetHistory(arg1:number):Promise<Array<main.HistoryItem>>;

export function GetRequestByID(arg1:number):Promise<main.HistoryItem>;

export function GetResponseByID(arg1:number):Promise<main.ResponseData>;

export function ParseCurlCommand(arg1:string):Promise<main.RequestData>;
